language: android
sudo: false

android:
  components:
    - tools
    - platform-tools
    - build-tools-31.0.0
    - android-31

before_install:
  - chmod +x gradlew
  - echo yes | sdkmanager "platforms;android-31"

script:
  - ./gradlew :mobile:jacocoTestReport

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
